# ── Application ──────────────────────────────────────────
spring.application.name=fraudshield
server.port=8080

# ── MongoDB Local (currently using) ──────────────────────
spring.data.mongodb.uri=mongodb://localhost:27017/test


# ── MongoDB Atlas (switch to this for production) ─────────


# ── JWT ──────────────────────────────────────────────────
jwt.secret=fraudshield-super-secret-key-2024-minimum-256-bits-long
jwt.expiration=86400000


# ── Logging ──────────────────────────────────────────────
logging.level.org.springframework.data.mongodb=DEBUG
logging.level.com.fraudshield=DEBUG


#kafka port number
spring.kafka.bootstrap-servers=localhost:9092

